image: node:lts-alpine

definitions:
  # Cached directories
  caches:
    node: ~/.npm
    turbo: .turbo

  # Define pipeline steps for reusability
  steps:
    - step: &checkCodeFormatting
        name: '🎨 Checking code formating'
        script:
          - npm run format:check

    - step: &runLinting
        name: '🧹 Running Lint Scanner'
        caches:
          - node
        script:
          - npm run lint

    # TODO: Configure unit test coverage step
    # - step: &unitTestingCoverage

    - step: &sonarqubeScan
        name: '🔎 Running SonarQube scanner'
        size: 2x # Increase container size
        script:
          - pipe: sonarsource/sonarqube-scan:2.0.1
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
    
    - step: &runMigrations
        name: '📁 Running Migrations'
        cache:
          - node
        script:
          - npm run db:migrate:deploy

    - step: &installDependencies
        name: '📦 Installing Dependencies'
        caches:
          - node
        script:
          - npm install

    - step: &buildAndPushDockerImage
        name: '📦 Build and push Docker image'
        services:
          - docker
        script:
          - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          # BITBUCKET_BUILD_NUMBER could be IMAGE_TAG as well
          - docker build ./apps/api -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_URL}:${BITBUCKET_REPO_SLUG}-${BITBUCKET_BUILD_NUMBER} 
          # The url could be changed
          - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_URL}:${BITBUCKET_REPO_SLUG}-${BITBUCKET_BUILD_NUMBER}

    - step: &deployDevelopment
        deployment: 'Development'
        name: '🚀 Deploying infrastructure'
        caches:
          - node
        script:
          - npx sst secrets set ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID} --stage development
          - npx sst secrets set SECRET_ACCESS_KEY_ID ${AWS_SECRET_ACCESS_KEY} --stage development
          - npx sst deploy --stage development

pipelines:
  branches:
    development:
      - step: *installDependencies
      - step: *runMigrations
      - parallel:
          - step: *generateBuild
          - step: *unitTestingCoverage
      - step: *buildAndPushDockerImage
      - parallel:
          - step: *sonarqubeAnalysis
          - step: *deployDevelopment
  
  pull-requests:
    '**':
      - step: *installDependencies
      - parallel:
          - step: *checkCodeFormating
          - step: *generateBuild
          - step: *unitTestingCoverage

  # Pipelines for manually deployments (Doesn't push a new image)
  custom:
    deployDevelopment:
      - step: *deployDevelopment
    deployStaging:
      - step: *deployStaging
